[package]
name = "bridgekeeper"
version = "0.1.0"
authors = ["Sebastian Woehrl <sebastian.woehrl@maibornwolff.de>"]
edition = "2018"

[dependencies]
log = "0.4.20"
kube = {version = "0.87.2", features = ["derive", "admission", "runtime"]}
k8s-openapi = { version = "0.20.0", default-features = false, features = ["v1_24"] }
schemars = "0.8.16"
serde = "1.0.195"
serde_derive = "1.0.195"
serde_json = "1.0.111"
serde_yaml = "0.9.30"
tokio = { version = "1.35.1", features = ["rt-multi-thread", "macros"]}
futures = "0.3.30"
pyo3 = "0.20.2"
pythonize = "0.20.0"
rcgen = "0.12.0"
base64 = "0.21.6"
argh = "0.1.12"
rust-embed = "8.2.0"
lazy_static = "1.4.0"
prometheus = { version = "0.13.3", default-features = false }
json-patch = "1.2.0"
exponential-backoff = "1.2.0"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", default-features = false, features = ["fmt", "json", "std", "registry"] } 
hyper = { version = "1.1.0", features = ["client"] }
axum = { version = "0.7.3" }
axum-server = { version = "0.6.0", features = ["tls-rustls"] }


[profile.release]
lto = false # Smaller size is not worth the compile time increase
# When a panic in a task occures we want the whole process to crash to trigger a kubernetes pod restart
panic = 'abort'
# Make binary smaller
debug = 0
strip = true
