[package]
name = "bridgekeeper"
version = "0.1.0"
authors = ["Sebastian Woehrl <sebastian.woehrl@maibornwolff.de>"]
edition = "2018"

[dependencies]
log = "0.4.20"
kube = {version = "0.85.0", features = ["derive", "admission", "runtime"]}
k8s-openapi = { version = "0.19.0", default-features = false, features = ["v1_24"] }
schemars = "0.8.13"
serde = "1.0.188"
serde_derive = "1.0.188"
serde_json = "1.0.105"
serde_yaml = "0.9.25"
tokio = { version = "1.32.0", features = ["rt-multi-thread", "macros"]}
futures = "0.3.28"
pyo3 = "0.19.2"
pythonize = "0.19.0"
rcgen = "0.11.1"
base64 = "0.21.3"
argh = "0.1.12"
rust-embed = "8.0.0"
lazy_static = "1.4.0"
prometheus = { version = "0.13.3", default-features = false }
json-patch = "1.0.0"
exponential-backoff = "1.2.0"
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", default-features = false, features = ["fmt", "json", "std", "registry"] } 
hyper = { version = "0.14.27", features = ["client"] }
axum = { version = "0.6.20" }
simple-hyper-server-tls = { version = "0.3.2", default-features = false, features = ["tls-openssl", "hyper-h1"] }


[profile.release]
lto = false # Smaller size is not worth the compile time increase
# When a panic in a task occures we want the whole process to crash to trigger a kubernetes pod restart
panic = 'abort'
# Make binary smaller
debug = 0
strip = true
