[package]
name = "bridgekeeper"
version = "0.1.0"
authors = ["Sebastian Woehrl <sebastian.woehrl@maibornwolff.de>"]
edition = "2018"

[dependencies]
log = "0.4.14"
simple_logger = {version = "1.11.0", default-features = false, features = ["chrono"] }
kube = {version = "0.58.1", features = ["derive", "admission"]}
kube-runtime = "0.58.1"
k8s-openapi = { version = "0.12.0", default-features = false, features = ["v1_19"] }
schemars = "0.8.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
serde_yaml = "0.8"
tokio = { version = "1.0", features=["rt-multi-thread", "macros", "sync"]}
futures = "0.3.15"
rocket = {version = "0.5.0-rc.1", features = ["tls", "json"]}
rustls = "0.19.0"
pyo3 = "0.14.1"
pythonize = "0.14.0"
rcgen = "0.8.11"
base64 = "0.13.0"
argh = "0.1.4"
rust-embed = "5.9.0"


[profile.release]
lto = true
opt-level = 'z'  # Optimize for size.
codegen-units = 1
#panic = 'abort'
