[package]
name = "bridgekeeper"
version = "0.1.0"
authors = ["Sebastian Woehrl <sebastian.woehrl@maibornwolff.de>"]
edition = "2018"

[dependencies]
log = "0.4.14"
simple_logger = {version = "1.13.0", default-features = false, features = ["chrono"] }
kube = {version = "0.72.0", features = ["derive", "admission", "runtime"]}
k8s-openapi = { version = "0.14.0", default-features = false, features = ["v1_19"] }
schemars = "0.8.6"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
serde_yaml = "0.8"
tokio = { version = "1.12.0", features = ["rt-multi-thread", "macros", "sync"]}
futures = "0.3.17"
rocket = {version = "0.5.0-rc.2", features = ["tls", "json"]}
rustls = "0.20.0"
pyo3 = "0.16.5"
pythonize = "0.16.0"
rcgen = "0.8.14"
base64 = "0.13.0"
argh = "0.1.6"
rust-embed = "6.2.0"
lazy_static = "1.4.0"
prometheus = {version = "0.13.0", features = ["process"]}


[profile.release]
lto = true
opt-level = 'z'  # Optimize for size.
codegen-units = 1
# When a panic in a task occures we want the whole process to crash to trigger a kubernetes pod restart
panic = 'abort'
