apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "bridgekeeper.labels" . | nindent 4 }}
  name: bridgekeeper-role
rules:
# During audit runs bridgekeeper needs to potentially access all resources in the cluster
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch
# The init job needs to create/update the webhook configurations
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations
  - validatingwebhookconfigurations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
# The init job needs to update namespaces with the ignore label
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - patch
  - update
# During audit runs bridgekeeper needs to update the policy status with the audit results
- apiGroups:
  - "bridgekeeper.maibornwolff.de"
  resources:
  - policies
  - policies/status
  - modules
  - modules/status
  verbs:
  - patch
  - update
# Bridgekeeper sends events for certain actions
- apiGroups:
  - ""
  - events.k8s.io
  resources:
  - events
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    {{- include "bridgekeeper.labels" . | nindent 4 }}
  name: bridgekeeper-role
  namespace: "{{ .Release.Namespace }}"
rules:
# The init job creates a secret with the TLS certificate, the main program needs to read it
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    {{- include "bridgekeeper.labels" . | nindent 4 }}
  name: bridgekeeper-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: bridgekeeper-role
subjects:
- kind: ServiceAccount
  name: {{ include "bridgekeeper.serviceAccountName" . }}
  namespace: "{{ .Release.Namespace }}"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    {{- include "bridgekeeper.labels" . | nindent 4 }}
  name: bridgekeeper-rolebinding
  namespace: "{{ .Release.Namespace }}"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: bridgekeeper-role
subjects:
- kind: ServiceAccount
  name: {{ include "bridgekeeper.serviceAccountName" . }}
  namespace: "{{ .Release.Namespace }}"
---
{{- if .Values.serviceAccount.extraClusterRole }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    {{- include "bridgekeeper.labels" . | nindent 4 }}
  name: bridgekeeper-extrarole
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.serviceAccount.extraClusterRole }}
subjects:
- kind: ServiceAccount
  name: {{ include "bridgekeeper.serviceAccountName" . }}
  namespace: "{{ .Release.Namespace }}"
{{- end }}
