apiVersion: apps/v1
kind: Deployment
metadata:
  name: add-label
  labels:
    app: nginx
    foobar: I-love-bridgekeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
