name: test
on: [pull_request]


jobs:
  unittests:
    name: Run unittests
    runs-on: ubuntu-latest
    env:
      CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse # Speed up initial build
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
            toolchain: "1.70.0"
            override: true
            components: clippy

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11' 
        
      - name: Compile code
        run: |
          cargo build
      
      - name: Run unit tests
        run: |
          set -e
          cargo test

      - name: Check clippy
        run: |
          set -e
          cargo clippy -- -D warnings # Fail on any warnings


  functionaltests:
    name: Run functional tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11' 

      - name: Setup k3d
        uses: nolar/setup-k3d-k3s@v1
        with:
          version: v1.24 # Test on the oldest kubernetes version we still want to support
          k3d-name: bridgekeeper-test
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run functional tests
        run: |
          set -e
          export DOCKER_IMAGE=bridgekeeper
          export DOCKER_TAG=test
          export DOCKER_VERSION=$DOCKER_IMAGE:$DOCKER_TAG
          export DOCKER_BUILDKIT=1
          docker build . -t $DOCKER_VERSION
          k3d image import -c bridgekeeper-test $DOCKER_VERSION
          helm install --namespace bridgekeeper --create-namespace bridgekeeper ./charts/bridgekeeper --set image.repository=$DOCKER_IMAGE --set image.tag=$DOCKER_TAG --wait
          cd functional_tests
          python execute_tests.py
